name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check
        run: npm run check
        
      # TypeScript check là quan trọng nhất - các bước khác có thể được bổ sung trong tương lai
      # - name: Lint
      #   run: npm run lint
      
  # Có thể thêm các job khác trong tương lai như test, security audit, v.v.